ROOMS = {
"ASG31":   {"desc":"", "size":100, "equip":("pc")},
"MFG15/16":{"desc":"", "size":None, "equip":("pc")},
"WM308":   {"desc":"", "size":5*6, "equip":("pc")},

"ECM-01A": {"desc":"mathlab", "size":None},
"ECM-01B": {"desc":"",        "size":None},
"ECM-15":  {"desc":"",        "size":None},
"ECM-15A": {"desc":"maclab",  "size":None, "equip":("mac")},
"ECM-18":  {"desc":"",        "size":6*6, "equip":("pc")},

"ECG-01":  {"desc":"",        "size":None},
"ECG-02":  {"desc":"",        "size":None},
"ECG-03":  {"desc":"",        "size":None, "equip":("pc")},
"ECG-04":  {"desc":"",        "size":None},
"ECG-12":  {"desc":"theta",   "size":None},
"ECG-13":  {"desc":"",        "size":None},
"ECG-14":  {"desc":"",        "size":None},
"ECG-15":  {"desc":"",        "size":None},
"ECG-24":  {"desc":"lecture", "size":None},
"ECG-26":  {"desc":"lecture", "size":None},
"ECG-27":  {"desc":"lecture", "size":None},
"ECG-35":  {"desc":"",        "size":None},
"ECG-36":  {"desc":"",        "size":None},

"EC1-01":  {"desc":"pclab",    "size":10*6, "equip":("pc")},
"EC1-02":  {"desc":"",         "size":None, "equip":("pc")},
"EC1-03":  {"desc":"",         "size":None},
"EC1-11":  {"desc":"",         "size":None},
"EC1-12":  {"desc":"",         "size":None},
"EC1-13":  {"desc":"ciscolab", "size":7*6, "equip":("pc")},
"EC1-14":  {"desc":"ehlab",    "size":7*6, "equip":("pc")},
"EC1-22":  {"desc":"",         "size":None},
"EC1-21":  {"desc":"",         "size":None},
"EC1-23":  {"desc":"",         "size":None},
"EC1-29":  {"desc":"",         "size":None},

"EC1-26":  {"desc":"",         "size":None},
"EC1-27A": {"desc":"planet",   "size":None},
"EC1-27B": {"desc":"planet",   "size":None},
"EC1-28":  {"desc":"planet",   "size":None},

"EC2-01":  {"desc":"",         "size":None},
"EC2-02":  {"desc":"",         "size":None},
"EC2-03":  {"desc":"",         "size":None},
"EC2-04":  {"desc":"eleclab",  "size":None},
"EC2-12":  {"desc":"",         "size":None},
"EC2-13":  {"desc":"",         "size":None},
"EC2-14":  {"desc":"gameslab", "size":None, "equip":("pc")},
"EC2-24":  {"desc":"planet",   "size":None},
"EC2-25":  {"desc":"planet",   "size":None}
}
